"""Core module for SupportBot AI platform."""

from core.config import AppConfig, config, get_config
from core.database import DatabaseManager, create_connection, db, get_connection, init_db
from core.models import (
    AssistantSettings,
    AssistantSettingsCreate,
    AssistantSettingsUpdate,
    Business,
    BusinessCreate,
    BusinessUpdate,
    Conversation,
    ConversationCreate,
    FAQ,
    FAQCreate,
    FAQUpdate,
    KnowledgeDocument,
    KnowledgeDocumentCreate,
    KnowledgeDocumentUpdate,
    Message,
    MessageCreate,
    Policy,
    PolicyCreate,
    PolicyUpdate,
    Product,
    ProductCreate,
    ProductUpdate,
)

__all__ = [
    "AppConfig",
    "config",
    "get_config",
    "DatabaseManager",
    "db",
    "init_db",
    "get_connection",
    "create_connection",
    "Business",
    "BusinessCreate",
    "BusinessUpdate",
    "AssistantSettings",
    "AssistantSettingsCreate",
    "AssistantSettingsUpdate",
    "Product",
    "ProductCreate",
    "ProductUpdate",
    "Policy",
    "PolicyCreate",
    "PolicyUpdate",
    "FAQ",
    "FAQCreate",
    "FAQUpdate",
    "KnowledgeDocument",
    "KnowledgeDocumentCreate",
    "KnowledgeDocumentUpdate",
    "Conversation",
    "ConversationCreate",
    "Message",
    "MessageCreate",
]
